### ISSUE TITLE
applications must write bytes

### ISSUE THREAD

**Issue by coreybrett** [spantaleev/flask-sijax#11]
I am trying to run the examples, but I keep getting "applications must write bytes".

Traceback (most recent call last):
  File "/home/cboyle/.virtualenvs/temp/lib/python2.7/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/home/cboyle/.virtualenvs/temp/lib/python2.7/site-packages/werkzeug/serving.py", line 168, in execute
    write(data)
  File "/home/cboyle/.virtualenvs/temp/lib/python2.7/site-packages/werkzeug/serving.py", line 148, in write
    assert type(data) is bytes, 'applications must write bytes'
AssertionError: applications must write bytes
^C(temp)cboyle@cbb2:~/Documents/temp$ python --version
Python 2.7.3

**Comment by Midnighter** [comment]
This is definitely related to the new `from __future__ import unicode_literals` or general `unicode` conversion. In Python 2 the `str` and `bytes` types are interchangeable, whereas the same is not true for Python 3 or the Python 2 `unicode` type. I thought I fixed this but I guess, I need to take a second look.

**Comment by coreybrett** [comment]
Could I just add `from __future__ import unicode_literals` to the top of the example files?

**Comment by Midnighter** [comment]
I'm sorry, I don't have the time to look into it right now, I'll do so over the weekend.

**Comment by Midnighter** [comment]
Just for my information: which flask-sijax and sijax versions are you using and which example was it exactly that failed here, or was it all of them?

**Comment by coreybrett** [comment]
I created and activated a fresh virtualenv on Debian Wheezy.

Ran "pip install flask"
Ran "pip install flask-sijax"

Downloaded the example code from github.

Ran the hello & chat apps. Same errors on both.

(venv)corey@117office:~/Documents/sijax/examples$ python hello.py
- Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
- Restarting with stat
  127.0.0.1 - - [31/Jan/2015 08:39:57] "GET / HTTP/1.1" 200 -
  127.0.0.1 - - [31/Jan/2015 08:39:58] "GET /favicon.ico HTTP/1.1" 404 -
  127.0.0.1 - - [31/Jan/2015 08:40:02] "GET /sijax HTTP/1.1" 200 -
  127.0.0.1 - - [31/Jan/2015 08:40:02] "GET /static/js/sijax/sijax.js
  HTTP/1.1" 200 -
  127.0.0.1 - - [31/Jan/2015 08:40:03] "POST /sijax HTTP/1.1" 200 -
  Error on request:
  Traceback (most recent call last):
  File
  "/home/corey/Documents/sijax/venv/lib/python2.7/site-packages/werkzeug/serving.py",
  line 180, in run_wsgi
  execute(self.server.app)
  File
  "/home/corey/Documents/sijax/venv/lib/python2.7/site-packages/werkzeug/serving.py",
  line 171, in execute
  write(data)
  File
  "/home/corey/Documents/sijax/venv/lib/python2.7/site-packages/werkzeug/serving.py",
  line 151, in write
  assert type(data) is bytes, 'applications must write bytes'
  AssertionError: applications must write bytes
  ^C(venv)corey@117office:~/Documents/sijax/examples$ python --version
  Python 2.7.3
  (venv)corey@117office:~/Documents/sijax/examples$ pip freeze
  Flask==0.10.1
  Flask-Sijax==0.4.1
  Jinja2==2.7.3
  MarkupSafe==0.23
  Sijax==0.3.0
  Werkzeug==0.10
  argparse==1.2.1
  distribute==0.6.24
  future==0.14.3
  itsdangerous==0.24
  wsgiref==0.1.2
  (venv)corey@117office:~/Documents/sijax/examples$

**Comment by Midnighter** [comment]
Alright, so I tested with Python 2.7.3 and 3.4.2 and it requires my other pull request to Sijax https://github.com/spantaleev/sijax-python/pull/8

The problem with the current Sijax version is that I converted the `json.dumps` to a `unicode` object. With the above pull request that is avoided. Honestly, now that I look at it again I'm a bit baffled that the `json.dumps` output doesn't need to be encoded to a `bytes` object but as far as I can tell it works.

So you can clone my branch https://github.com/Midnighter/sijax-python/tree/configure_json or wait for @spantaleev to merge and upload another version to PyPI.

**Comment by spantaleev** [comment]
Seems like it's already fixed by the new Sijax version (0.3.1), thanks to @Midnighter!

**Comment by RoboMod** [comment]
I'm sorry to say, but the update of Sijax only fixed this bug for examples hello.py and chat.py. Running comet.py or upload.py still results in the reportet traceback (see first entry by coreybrett). I think there is some problem around the `yield` command which is not used in hello.py/chat.py.

**Comment by coreybrett** [comment]
I confirm what RoboMod reported.

**Comment by RoboMod** [comment]
I think there are two ways to solve this problem:
1.) change the algorithm (e.g. use WebSockets instead of Comet)
2.) allow transmitting non-JSON strings in combination with werkzeug

Would be nice to take option 2. Are there any ideas how to fix the JSON "bug" in werkzeug?

edit: Should be fixed; was easier than thought ;)

**Comment by macfire** [comment]
I am also receiving the error "must write bytes" in upload.py and comet.py 

```
 File ".../venv/lib/python3.4/site-packages/werkzeug/serving.py", line 151, in write 
     assert type(data) is bytes, 'applications must write bytes'
AssertionError: applications must write bytes
```

Using:
- Python 3.4.2
- Flask 0.10.1
- Sijax 0.3.1
- Flask-Sijax 0.4.1

Is there a newer version of Sijax or Flask-Sijax I should be using?

**Comment by Midnighter** [comment]
https://github.com/spantaleev/sijax-python/issues/10 Fixes the issue in Sijax but has not been merged yet.

**Comment by macfire** [comment]
@Midnighter , thank you. That works.
