### ISSUE TITLE
Python Flask Frame work

### ISSUE THREAD

**Issue by adireddys** [spantaleev/flask-sijax#16]
I installed my desktop with 
FLASK-0.11
Werkzeug>=0.7',
        'Jinja2>=2.4',
        ',
        'click>=6.6'
itsdangerous>=2.4xcd

and i run the simple hello.py

from flask import Flask
app = Flask(__name__)

@app.route("/")
def hello():
    return "Hello World!"

if __name__ == "__main__":
    app.run(debug=True)

I am getting the below error. Can any one help me whether it is a network setting issue or any other issue

![untitled](https://cloud.githubusercontent.com/assets/22215350/20699568/fa5064de-b62d-11e6-89a1-b7ce5dfceb1b.png)

**Comment by spantaleev** [comment]
Seems like the error is in `flask/app.py` on line `1993`.

Looking at your Flask version (`0.11.3`), it seems like the bug should likely be here: https://github.com/pallets/flask/blob/0.11.1/flask/app.py#L1994

From what I see there, however, I don't see any problem.

You seem to be running Python 3.5, so I wonder if that creates some problem..

**Comment by adireddys** [comment]
I fix that error.. by replacing the flask 0.11-- app.py with flask 0.11.1
-- app.py.

**Comment by spantaleev** [comment]
Oh, yeah.. You were on `0.11`. I incorrectly saw that as `0.11.3`, which is not even available.
